version: '3.4'

services:
  postgres:
    image: 'bitnami/postgresql:latest'
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=meetme
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'

volumes:
  postgresql_data:
    driver: local
