version: '3.4'

services:
  mysql:
    image: 'mysql:latest'
    environment:
      - MYSQL_ROOT_PASSWORD=docker
    ports:
      - '3306:3306'
    volumes:
      - 'mysql_data:/var/lib/mysql'

volumes:
  mysql_data:
    driver: local
